#!/usr/bin/env python3
"""Move expenses and payments from the Python app into the Swift one.

Reads the Python app's own API rather than PocketBase directly, so the export is exactly what that
app considers its state, and writes SQL to stdout instead of touching the database, so the
statements can be read before they are applied.

    ./migrate-from-pocketbase.py --source http://old-app:8000 --user you > migration.sql

The period markers ("last_paid_period") are copied verbatim, which is only safe because the source
data holds none of the frequencies the Python app recorded wrongly. The script refuses to run if it
finds any, rather than quietly importing a period the new app cannot read: it stamped a bare year on
quarterly, semi-annual and biweekly expenses, while the status check compares those against
"YYYY-MM" and "YYYY-Www".
"""

import argparse
import json
import sys
import urllib.request
import uuid

# Frequencies whose period markers the Python app wrote in a format the Swift app cannot read.
UNSAFE_FREQUENCIES = {"quarterly", "semi_annual", "biweekly"}


def fetch(base, path, user):
    request = urllib.request.Request(f"{base}{path}", headers={"X-Forwarded-User": user})
    with urllib.request.urlopen(request, timeout=30) as response:
        return json.load(response)


def sql_string(value):
    if value is None:
        return "NULL"
    return "'" + str(value).replace("'", "''") + "'"


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--source", required=True, help="base URL of the Python app")
    parser.add_argument("--user", default="admin", help="value for the X-Forwarded-User header")
    parser.add_argument(
        "--allow-unsafe-periods",
        action="store_true",
        help="import frequencies whose period markers the old app wrote wrongly, clearing them",
    )
    args = parser.parse_args()

    dashboard = fetch(args.source, "/api/expenses", args.user)
    payments = fetch(args.source, "/api/payments", args.user)
    expenses = dashboard["expenses"]

    unsafe = [e for e in expenses if e["frequency"] in UNSAFE_FREQUENCIES]
    if unsafe and not args.allow_unsafe_periods:
        print(
            f"Refusing to run: {len(unsafe)} expense(s) use a frequency whose period marker the "
            f"old app wrote in a format the new one cannot read "
            f"({', '.join(sorted({e['frequency'] for e in unsafe}))}).\n"
            f"Re-run with --allow-unsafe-periods to import them with the marker cleared, which "
            f"shows them as unpaid for the current cycle.",
            file=sys.stderr,
        )
        return 1

    # Old ids are PocketBase strings; the new schema uses UUIDs, so payments are rewired by name.
    ids = {expense["id"]: str(uuid.uuid4()) for expense in expenses}

    print("-- Generated by scripts/migrate-from-pocketbase.py")
    print(f"-- Source: {args.source} — {len(expenses)} expenses, {len(payments)} payments")
    print("BEGIN;")
    print()

    for expense in expenses:
        period = expense.get("last_paid_period") or ""
        if expense["frequency"] in UNSAFE_FREQUENCIES:
            period = ""

        print(
            "INSERT INTO expenses "
            "(id, name, amount, frequency, due_day, due_month, category, last_paid_period, "
            "active, is_variable, created_at, updated_at) VALUES ("
            f"{sql_string(ids[expense['id']])}::uuid, "
            f"{sql_string(expense['name'])}, "
            f"{float(expense['amount'])}, "
            f"{sql_string(expense['frequency'])}::frequency, "
            f"{int(expense['due_day'])}, "
            f"{expense['due_month'] if expense.get('due_month') else 'NULL'}, "
            f"{sql_string(expense['category'])}, "
            f"{sql_string(period)}, "
            f"{'true' if expense.get('active', True) else 'false'}, "
            f"{'true' if expense.get('is_variable') else 'false'}, "
            "now(), now());"
        )

    print()
    for payment in payments:
        expense_id = ids.get(payment.get("expense_id"))
        if expense_id is None:
            print(f"-- Skipped payment {payment.get('id')}: its expense is gone from the source")
            continue

        print(
            "INSERT INTO payments "
            "(id, expense_id, amount_paid, date_paid, period, paid_by, created_at) VALUES ("
            f"{sql_string(str(uuid.uuid4()))}::uuid, "
            f"{sql_string(expense_id)}::uuid, "
            f"{float(payment['amount_paid'])}, "
            f"{sql_string(payment['date_paid'])}::date, "
            f"{sql_string(payment.get('period', ''))}, "
            f"{sql_string(payment.get('paid_by') or 'migracja')}, "
            "now());"
        )

    print()
    print("COMMIT;")
    return 0


if __name__ == "__main__":
    sys.exit(main())
